<<<<<<< HEAD
spring:
  profiles:
    active: dev
  application:
    name: config-client
  eureka:
    client:
      service-url:
        defaultZone: http://admin:123456@localhost:8761/eureka/
    instance:
      status-page-url-path: http://localhost:8007/info
      health-check-url-path: http://localhost:8007/health
      prefer-ip-address: true
      instance-id: config-client
---
spring:
  profiles: test

server:
  port: 8008

---
spring:
  profiles: dev

server:
  port: 8009
=======
uaser:
  name: 李佳dev
  password: 123456dev
>>>>>>> d87f7840f553c90f8602dd6eedf01befe2bc3184
