server:
  port: 8888
spring:
  application:
    name:  config-server
eureka:
  client:
    service-url:
     defaultZone: http://admin:123456@localhost:8761/eureka/
  instance:
    status-page-url-path: http://localhost:8888/info
    health-check-url-path: http://localhost:8888/health
    prefer-ip-address: true
    instance-id: config-server
