
spring:
  profiles:
    active: dev


  
---
spring:
  profiles: test
  application:
    name: config-test


---
spring:
  profiles: dev
  application:
    name: config-dev

uaser:
  name: 李佳dev
  password: 123456dev
